package com.automationteststore.support;

import com.automationteststore.core.config.ConfigManager;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

/**
 * JUnit 5 extension that writes environment.properties to target/allure-results/
 * exactly once per test run, so the Allure report can display the environment panel.
 *
 * Register via @ExtendWith(AllureEnvironmentExtension.class) on BaseTest.
 */
public class AllureEnvironmentExtension implements BeforeAllCallback, ExtensionContext.Store.CloseableResource {

    private static final String STORE_KEY = "allure-environment-written";
    private static final Path ALLURE_RESULTS_DIR = Paths.get("target", "allure-results");

    @Override
    public void beforeAll(ExtensionContext context) throws Exception {
        ExtensionContext.Store globalStore = context.getRoot()
                .getStore(ExtensionContext.Namespace.GLOBAL);

        // Only execute once across the whole test run
        if (globalStore.get(STORE_KEY) == null) {
            globalStore.put(STORE_KEY, this);
            writeEnvironmentProperties();
        }
    }

    @Override
    public void close() {
        // no-op – cleanup not needed
    }

    private void writeEnvironmentProperties() throws IOException {
        Files.createDirectories(ALLURE_RESULTS_DIR);

        String browser = capitalise(ConfigManager.getString("browser"));
        String headless = ConfigManager.getBoolean("headless", true) ? "Yes" : "No";
        String baseUrl = ConfigManager.getString("baseUrl");
        int timeout = ConfigManager.getInt("timeout.seconds", 15);

        Properties props = new Properties();
        props.setProperty("Environment", "Test");
        props.setProperty("Base.URL", baseUrl);
        props.setProperty("Browser", browser);
        props.setProperty("Headless", headless);
        props.setProperty("Timeout.Seconds", String.valueOf(timeout));
        props.setProperty("OS", System.getProperty("os.name") + " " + System.getProperty("os.arch"));
        props.setProperty("Java.Version", System.getProperty("java.version"));
        props.setProperty("Framework", "Selenium 4 + JUnit 5 + Allure");

        Path target = ALLURE_RESULTS_DIR.resolve("environment.properties");
        try (OutputStream out = Files.newOutputStream(target)) {
            props.store(out, "Allure Environment — auto-generated by AllureEnvironmentExtension");
        }
    }

    private static String capitalise(String value) {
        if (value == null || value.isBlank()) return value;
        return Character.toUpperCase(value.charAt(0)) + value.substring(1).toLowerCase();
    }
}

